### ISSUE TITLE
mydefichain DMC Testnet: <Issue Title>

### ISSUE THREAD

**Issue by shantonio** [mydefichain/blockscout#1]
This is my address . 0xB106af381A0519f4B3919d522322D4768a87758e

now I have  110 DFI   

but if I see under transactions I see only 10 DFI as input  
https://testnet-dmc.mydefichain.com:8444/address/0xB106af381A0519f4B3919d522322D4768a87758e/transactions?filter=to#address-tabs

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

*Tell us what should happen.*
it should be seen more as 1  transactions

### Actual Behaviour

*Tell us what happens instead.*

**Comment by mydefichain** [comment]
Testnet has rollback. Input from transferdomain are not vissiboel as transaction.
